[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive", "cargo"] }
sqlx = { version = "0.7.2", features = ["sqlite"] }
tokio = { version = "1.34.0", features = ["full"] }

